[FAL-229] Docker devstack for cert-manager
open-craft/cert-manager pull request #23
Opened 2021-07-07 23:53 UTC by ChrisChV

Simple devstack added to run the unit tests easily

**Jira tciket:** [FAL-229](https://tasks.opencraft.com/browse/FAL-229)

- New docker-compose.yml file added that creates one container running the consul service and another with python3.6
- New Makefile.yml file added with commands to start/stop/destroy the devstack and one command to run the unit tests on the python3.6 container
- README.md updated with this new way to run tests

2021-07-08 01:31 UTC, swalladge requested changes
@ChrisChV looks good, and works perfectly!  I left some requests mainly about style changes. :)

2021-07-08 01:31 UTC, swalladge commented on Makefile
> +	docker-compose -f docker-compose.yml up -d
@ChrisChV `-f docker-compose.yml` can be omitted, because this is the default value.

2021-07-08 01:31 UTC, swalladge commented on Makefile
> +	docker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -it cert-manager.devstack.test /bin/bash /opt/scripts/run_tests.sh
Please configure your editor to properly add the final newline at the end of files. :)

2021-07-08 01:31 UTC, swalladge commented on docker-compose.yml
> +      - "$PWD:/opt/"
Check for trailing whitespace. ;)

2021-07-08 01:31 UTC, swalladge commented on docker-compose.yml
> +      CONSUL_HTTP_ADDR: 192.168.176.3:8500
The custom networks can be removed, and this value replaced with `cert-manager.devstack.consul:8500` (relying on docker's pseudo dns system).

2021-07-08 13:16 UTC, mtyaka commented on README.md
> +To run the unit tests in a devstack (containers), you need to start the devstack:
Can we replace "containers" with "docker" just to make it more obvious that you need to have docker installed for this to work?

2021-07-12 06:23 UTC, mtyaka commented on scripts/run_tests.sh
> +python -m pipenv run pytest
Nit: no newline at end of file

2021-07-12 07:25 UTC, mtyaka commented
Nice work! Please add the missing newline, but then you can go ahead and merge :+1:

- [x] I tested this: I verified that the make commands work perfectly.
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ n/a
- [x] Includes documentation

2021-07-12 07:44 UTC, swalladge approved these changes

2021-07-12 19:17 UTC, merged